# ===========================
# Application
# ===========================
spring.application.name=hostel-management
server.port=8080
server.servlet.context-path=/api

# ===========================
# MySQL DataSource
# ===========================
spring.datasource.url=jdbc:postgresql://dpg-d6rsvsndiees73c0s62g-a.oregon-postgres.render.com:5432/hostel_db_gh0l
spring.datasource.username=hostel_db_gh0l_user
spring.datasource.password=LwkLuzX1mU2A6mGlRRkJZMXP53WrmJbE
spring.jpa.database-platform=source.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===========================
# JPA / Hibernate
# ===========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# ===========================
# JWT
# ===========================
app.jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
app.jwt.expiration-ms=86400000

# ===========================
# CORS
# ===========================
app.cors.allowed-origins=http://localhost:3000

# ===========================
# Logging
# ===========================
logging.level.org.springframework.security=DEBUG
logging.level.com.hostel=DEBUG
#postgresql://hostel_db_gh0l_user:
